# QIIME 2
# Get full file from from https://qiime2.org/
q2env: "envs/qiime2-amplicon-2024.2-py38-osx-conda.yml"

# GTDB options
gtdb_opt:
    version: "214.1"
    domain: "Both"
    db: "SpeciesReps"

# Primers
primers:
    'v1v3':
        'fw': 'AGAGTTTGATYMTGGCTCAG'
        'rev': 'GCTGCCTCCCGTAGGAGT'
    'v3v4':
        'fw': 'GTGYCAGCMGCCGCGGTAA'
        'rev': 'GGACTACNVGGGTWTCTAAT'
    'v4':
        'fw': 'CCTACGGGNGGCWGCAG'
        'rev': 'GACTACHVGGGTATCTAATCC'
    'v4v5':
        'fw' : 'GTGYCAGCMGCCGCGGTAA'
        'rev' : 'CCGYCAATTYMTTTRAGTTT'
    'v6v8':
        'fw': 'GAATTGACGGGGGCCCGCACAAG'
        'rev': 'CGGTGTGTACAAGGCCCGGGAACG'
    'v7v9':
        'fw': 'CAACGAGCGCAACCCT'
        'rev': 'TACGGYTACCTTGTTACGACTT'

# output directory
outdir: 'results'